apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8082
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    k8s-app: heapster
