apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chronograf
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: chronograf
        task: monitoring
    spec:
      volumes:
      - name: chronograf-storage
        emptyDir: {}
      containers:
      - name: chronograf
        image: chronograf:1.0.0-rc1
        ports:
          - containerPort: 10000
            protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/chronograf
          name: chronograf-storage
