apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    app: chronograf
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Chronograf
  name: chronograf
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  type: LoadBalancer
  # type: NodePort
  ports:
  - port: 80
    targetPort: 10000
  selector:
    service: chronograf
