apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    app: grafana
    kubernetes.io/name: Grafana
  name: grafana
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  type: LoadBalancer
  # type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    service: grafana
