apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    app: influxdb
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: InfluxDB
  name: influxdb
  namespace: kube-system
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    service: influxdb
