apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
  name: influxdb
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    service: influxdb
