apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: influxdb
        task: monitoring
    spec:
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.6
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
