apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
  name: monitoring-influx-grafana-controller
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      containers:
        - image: kubernetes/heapster_influxdb:v0.3
          name: influxdb
          ports:
            - containerPort: 8083
              hostPort: 8083
            - containerPort: 8086
              hostPort: 8086
        - name: grafana
          image: kubernetes/heapster_grafana:v0.6
          ports:
              - containerPort: 80
          env:
            - name: "HTTP_USER"
              value: "admin"
            - name: "HTTP_PASS"
              value: "**None**"
            - name: "INFLUXDB_METRICS_URL"
              value: "/api/v1beta3/proxy/namespaces/default/services/monitoring-influxdb/db/k8s"
            - name: "INFLUXDB_GRAFANA_URL"
              value: "/api/v1beta3/proxy/namespaces/default/services/monitoring-influxdb/db/grafana"
